version: "3.7"
services:
  cloakr:
    image: beyondcodegmbh/cloakr-server:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8080:${PORT}
    environment:
      port: ${PORT}
      domain: ${DOMAIN}
      username: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}
    restart: always
    volumes:
      - ./database/cloakr.db:/root/.cloakr
