blank_issues_enabled: false
contact_links:
  - name: Check the docs
    url: https://cloakr.dev/docs/introduction
    about: "This repository contains the open source version of Cloakr. Please contact our email support if you have issues with our network or Cloakr Pro!"
  - name: Security vulnerabilities
    url: https://@beyondco.de
    about: If you want to report a security issue, please contact our support.
